#!/usr/bin/env bash
# PreToolUse(Write|Edit): refuse direct edits to openspec/specs/**.
#
# Those files are generated by `openspec archive` from a change's delta specs. Editing them by
# hand puts the specs and the change history out of agreement, silently.
#
# One narrow exception: an Edit whose old_string is exactly the archiver's own `## Purpose`
# stub. openspec-workflow.md rule 12 requires filling that placeholder in after every archive,
# so this hook must not block the one edit its own workflow mandates. Anything else — a Write
# (whole-file replace) or an Edit touching any other text — is still denied.
set -u

payload=$(cat)

json_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r "$1 // empty"
  else
    printf '%s' "$payload" | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{try{const j=JSON.parse(s);process.stdout.write($2||'')}catch(e){}})"
  fi
}

file=$(json_field '.tool_input.file_path' '(j.tool_input&&j.tool_input.file_path)')
[ -n "$file" ] || exit 0
file=${file//\\//}

case "$file" in
  */openspec/specs/*|openspec/specs/*) ;;
  *) exit 0 ;;
esac

tool_name=$(json_field '.tool_name' '(j.tool_name)')
old_string=$(json_field '.tool_input.old_string' '(j.tool_input&&j.tool_input.old_string)')

case "$tool_name" in
  Edit)
    case "$old_string" in
      *"TBD - created by archiving change"*) exit 0 ;;
    esac
    ;;
esac

reason="openspec/specs/** is generated by \`openspec archive\` from a change's delta specs and must not be edited directly. Put the change in openspec/changes/<change>/specs/<capability>/spec.md as an ADDED/MODIFIED/REMOVED delta, then archive it. The one exception is replacing the generated \`## Purpose\` stub (\`TBD - created by archiving change ...\`), which openspec-workflow.md requires."

if command -v jq >/dev/null 2>&1; then
  jq -nc --arg r "$reason" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
else
  node -e 'process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:process.argv[1]}}))' "$reason"
fi
exit 0
