#!/usr/bin/env bash
# PreToolUse(Write|Edit): refuse direct edits to openspec/specs/**.
#
# Those files are generated by `openspec archive` from a change's delta specs. Editing them by
# hand puts the specs and the change history out of agreement, silently.
set -u

read_path() {
  if command -v jq >/dev/null 2>&1; then
    jq -r '.tool_input.file_path // empty'
  else
    node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const j=JSON.parse(s);process.stdout.write((j.tool_input&&j.tool_input.file_path)||"")}catch(e){}})'
  fi
}

file=$(read_path)
[ -n "$file" ] || exit 0
file=${file//\\//}

case "$file" in
  */openspec/specs/*|openspec/specs/*) ;;
  *) exit 0 ;;
esac

reason="openspec/specs/** is generated by \`openspec archive\` from a change's delta specs and must not be edited directly. Put the change in openspec/changes/<change>/specs/<capability>/spec.md as an ADDED/MODIFIED/REMOVED delta, then archive it."

if command -v jq >/dev/null 2>&1; then
  jq -nc --arg r "$reason" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
else
  node -e 'process.stdout.write(JSON.stringify({hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:process.argv[1]}}))' "$reason"
fi
exit 0
